name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
- name: Setup CocoaPods
   run: |
        pod install || pod update

  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies
        run: brew install --formula cocoapods

      - name: Build Project
        run: xcodebuild -project AudioRecorderApp.xcodeproj -scheme AudioRecorderApp -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
