name: Build Android & iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Android App
        run: ./gradlew assembleRelease

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure iOS directory exists
        run: |
          if [ ! -d "ios" ]; then
            echo "iOS directory not found, creating..."
            mkdir ios
          fi

      - name: Install dependencies
        run: |
          brew install --formula cocoapods
          cd ios && pod install

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace AudioRecorderApp.xcworkspace \
            -scheme AudioRecorderApp \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
